### ISSUE TITLE
Format doesn't respect expandtab

### ISSUE THREAD

**Issue by jonringer** [jjo/vim-cue#14]
The format function will replace spaces with tabs, really surprising behavior. Currently I just have the auto_save turned off.

**Comment by myitcv** [comment]
@jonringer like Go, CUE is opinionated about the fact that formatting uses tabs for indentation and blanks for alignment. The format function provided by this plugin simply delegates to `cue fmt`. Hence there are no options as far as `cue fmt` is concerned. 

Instead, you can set `shiftwidth` and `tabwidth` in Vim to control how a tab is rendered. For example I set:

```
" $HOME/.vim/ftplugin/cue.vim

setlocal ts=3
setlocal sw=3
```

**Comment by jjo** [comment]
Thanks @myitcv for the details, closing as it's actually working as expected.
